# version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  web:
    build: ./web
    volumes:
      - ./web:/var/www/html
      - ./shared/queue:/queue
    ports:
      - "8080:80"
    env_file: .env
    depends_on:
      - db
  fetcher:
    build: ./fetcher
    env_file: .env
    volumes:
      - ./shared/queue:/queue
    depends_on: [db]
volumes:
  pgdata: